- README.md
> products model

- client/components/user-home.js
- script/seed.js
- server/api/users.js
- server/db/models/user.js
> Sams branch

- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/routes.js
- client/store/singleProduct.js
- script/seed.js
- server/api/products.js
- server/db/models/index.js
> single product view added

- client/store/cart.js
- script/seed.js
- server/api/cart.js
> Julia branch

- client/components/cart.js
> feat: added fucntional  delete button to each item

- .gitignore
> deleted bundle.js

- .gitignore
- client/components/Login.js
- client/components/SignUp.js
- client/components/navbar.js
- client/routes.js
- client/store/user.js
> Branch de la lindsey

- .travis.yml
> edited yml file

- server/db/db.js
> postgres fix

- .travis.yml
- server/api/cart.js
> postgres version change

- client/components/cart.js
> small fix on cart component

- server/api/cart.js
> cart patch B)

- client/components/cart.js
- client/store/cart.js
- server/api/cart.js
- server/api/products.js
- server/api/users.js
> Julia monday

- client/components/AdminCustomers.js
- client/components/AdminInventory.js
- client/components/AdminOrders.js
- client/components/Navbar.js
- client/routes.js
> Lindsey monday5

- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/store/cart.js
- client/store/cartItem.js
- server/api/cart.js
> Priscila mon2

- client/components/AboutUs.js
- client/components/AdminAddNewProd.js
- client/components/AdminEditProd.js
- client/components/AdminInventory.js
- client/components/AllProducts.js
- client/components/Navbar.js
- client/routes.js
- server/api/cart.js
- server/db/models/cart.js
> Lindsey monday6

- client/components/AllProducts.js
- server/api/cart.js
> Priscila tue

- client/components/cart.js
- client/store/cart.js
- script/seed.js
- server/api/cart.js
- server/api/users.spec.js
> Julia tues2

- client/components/AdminAddNewProd.js
- client/components/AdminEditProd.js
- client/components/AdminInventory.js
- client/store/products.js
- server/api/products.js
> Lindsey tuesday2

- client/components/AboutUs.js
> small edits to about us page

- client/components/CustomerOrders.js
- client/components/Navbar.js
- server/api/cart.js
- server/db/models/cartItems.js
> Sam order history

- client/components/Login.js
- client/components/Navbar.js
- client/routes.js
- client/store/user.js
> pushes to /login route upon logout, pushes to /home route upon sign in
